Duurzame-Consumentkeuzes/Models/Device.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Policy;

namespace Duurzame_Consumentkeuzes.Models
{
    public class Device
    {
        public int Id { get; set; }
        public string? Name { get; set; }    
        public string? Brand { get; set; }
        public string? Type { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Price { get; set; }
        public DateTime? BuildDate { get; set; }
        public ICollection<Customer>? Customers { get; set; }    
        public EnergyLabel? EnergyLabel { get; set; }
        public int? EnergyLabelId { get; set; }
        public string? ImagePath { get; set; }
    }
}

Duurzame-Consumentkeuzes/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duurzame_Consumentkeuzes.Data;
using Duurzame_Consumentkeuzes.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Duurzame_Consumentkeuzes.Controllers
{
    public class DevicesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Customer> userManager;

        public DevicesController(ApplicationDbContext context, UserManager<Customer> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index(int? energyLabelId, bool showAll, string? brand, string? type)

        {
            var currentUser = await userManager.GetUserAsync(User);
            IQueryable<Device> query = _context.Devices.Include(d => d.EnergyLabel);

            var uniqueBrands = _context.Devices.Select(d => d.Brand).Distinct().ToList();
            var uniqueType = _context.Devices.Select(d => d.Type).Distinct().ToList();
            ViewBag.Brands = uniqueBrands;
            ViewBag.Type = uniqueType;



            if (showAll == true)
            {
                var allDevices = await query.ToListAsync();
                return View(allDevices);
            }

            if (energyLabelId.HasValue)
            {
                query = query.Where(d => d.EnergyLabelId <= energyLabelId);
            }

            if (!string.IsNullOrEmpty(brand))
            {
                query = query.Where(d => d.Brand == brand);
            }
            if (!string.IsNullOrEmpty(type))
            {
                query = query.Where(d => d.Type == type);
            }

            if (currentUser.Budget.HasValue)
            {
                ViewBag.UserBudget = currentUser.Budget;
                query = query.Where(d => d.Price <= currentUser.Budget);
            }

            var filteredDevices = await query.ToListAsync();
            return View(filteredDevices);
        }

        // GET: Devices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // GET: Devices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Brand,Type,Price,BuildDate,EnergyLabelId,ImagePath")] Device device)
        {
            if (ModelState.IsValid)
            {
                _context.Add(device);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices.FindAsync(id);
            if (device == null)
            {
                return NotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Brand,Type,Price,BuildDate,EnergyLabelId,ImagePath")] Device device)
        {
            if (id != device.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(device);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Devices == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");
            }
            var device = await _context.Devices.FindAsync(id);
            if (device != null)
            {
                _context.Devices.Remove(device);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeviceExists(int id)
        {
          return (_context.Devices?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Duurzame-Consumentkeuzes/Views/Devices/Create.cshtml
@model Duurzame_Consumentkeuzes.Models.Device

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Device</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuildDate" class="control-label"></label>
                <input asp-for="BuildDate" class="form-control" />
                <span asp-validation-for="BuildDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnergyLabelId" class="control-label"></label>
                <select asp-for="EnergyLabelId" class ="form-control" asp-items="ViewBag.EnergyLabelId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Duurzame-Consumentkeuzes/Views/Devices/Delete.cshtml
@model Duurzame_Consumentkeuzes.Models.Device

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BuildDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BuildDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Duurzame-Consumentkeuzes/Views/Devices/Details.cshtml
@model Duurzame_Consumentkeuzes.Models.Device

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BuildDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BuildDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Duurzame-Consumentkeuzes/Views/Devices/Edit.cshtml
@model Duurzame_Consumentkeuzes.Models.Device

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Device</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuildDate" class="control-label"></label>
                <input asp-for="BuildDate" class="form-control" />
                <span asp-validation-for="BuildDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnergyLabelId" class="control-label"></label>
                <select asp-for="EnergyLabelId" class="form-control" asp-items="ViewBag.EnergyLabelId"></select>
                <span asp-validation-for="EnergyLabelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Duurzame-Consumentkeuzes/Views/Devices/Index.cshtml
@model IEnumerable<Duurzame_Consumentkeuzes.Models.Device>

@{
    ViewData["Title"] = "Index";
}

<h1>Apparaten</h1>
<p>Op deze pagina vindt u een door ons aanbevolen assortiment aan huishoudelijke apparaten!</p>
<br />

<form asp-controller="Devices" asp-action="Index" method="get" class="filterSection">
    <div class="form-group">
        <label for="energyLabelId">Minimaal Energy Label:</label>
        <select id="energyLabelId" name="energyLabelId">
            <option value="">Any</option>
            <option value="1">A</option>
            <option value="2">B</option>
            <option value="3">C</option>
            <option value="4">D</option>
            <option value="5">E</option>
            <option value="6">F</option>
            <option value="7">G</option>
        </select>
    </div>

    <div class="form-group">
        <label for="type">Filter op type apparaat:</label>
        <select id="type" name="type">
            <option value="">alle</option>
            @foreach (var deviceType in ViewBag.Type)
            {
                <option value="@deviceType">@deviceType</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label for="brand">Filter op merk:</label>
        <select id="brand" name="brand">
            <option value="">alle</option>
            @foreach (var brand in ViewBag.Brands)
            {
                <option value="@brand">@brand</option>
            }
        </select>
    </div>

    <p>Je budget is: @ViewBag.UserBudget</p>



    <button class="btn btn-primary custom-btn" type="submit">Apply Filters</button>
</form>


<form asp-controller="Devices" asp-action="Index" method="get">
    <input type="hidden" name="showAll" value="true" />
    <button class="btn btn-primary custom-btn" type="submit">Laat alle apparaten zien</button>
</form>



@* @{
    List<string> types = new List<string>();
    foreach (var item in Model)
    {
        if (!types.Contains(item.Type))
        {
            types.Add(item.Type);
        }
    }
    foreach (string type in types)
    {
        <h2>@type</h2>
        
        List<Device> devices = new List<Device>();
        foreach (var item in Model)
        {
            if (item.Type == type)
            {
                devices.Add(item);
            }
        }
        <p>Aantal: @devices.Count()</p>

        <table*>
            @{
                int rowCount = (int)Math.Ceiling(((double)devices.Count() / 5));
                for (int r = rowCount; r > 0; r--)
                {
                    <tr>
                        @for (int i = 0; i < 5; i++)
                        {
                            @if (devices.Count == 0)
                            {
                                <td></td>
                            }

                            else
                            {
                                <td class="deviceItem">
                                    <table>
                                        <tr>
                                            <td>
                                                <img src="@devices[devices.Count() - 1].ImagePath" class="deviceImage">
                                            </td>
                                            <td>
                                                @devices[devices.Count() - 1].Name <br />
                                                Energieklasse: <img src="@devices[devices.Count() - 1].EnergyLabel.ImagePath"> <br />
                                                Prijs: €@devices[devices.Count() - 1].Price
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                devices.RemoveAt(devices.Count() - 1);
                            }                                                                          
                        }                        
                    </tr>
                }
            }                          
        </table*>
        <br />
    }
} *@

@{
    List<string> types = new List<string>();
    foreach (var item in Model)
    {
        if (!types.Contains(item.Type))
        {
            types.Add(item.Type);
        }
    }
    foreach (string type in types)
    {
        <h2>@type</h2>

        List<Device> devices = new List<Device>();
        foreach (var item in Model)
        {
            if (item.Type == type)
            {
                devices.Add(item);
            }
        }
        <p>Aantal: @devices.Count()</p>

        <div style="display: flex; flex-wrap: wrap;">
            
            @for (int i = 0; i < devices.Count; i++)
            {
                <div class="device-container">
                    <img src="@devices[i].ImagePath" class="deviceImage">
                    <p>@devices[i].Name</p>
                    <p>Energieklasse: <img src="@devices[i].EnergyLabel.ImagePath"></p>
                    <p>Prijs: €@devices[i].Price</p>
                </div>
            }
        </div>
        <br />
    }
}